# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Chromatic

on: push

env:
  node-version: "16.17.1"

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: "npm"
      - run: npm ci
      - uses: chromaui/action@v1
        id: chromatic
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          zip: true
      # find PR number and assign it to "steps.find-pr.outputs.number"
      - run: echo "number=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_OUTPUT
        id: find-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # comment to PR if PR exists
      - uses: marocchino/sticky-pull-request-comment@v1
        if: success() && steps.find-pr.outputs.number
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: chromatic-notification
          number: ${{ steps.find-pr.outputs.number }}
          recreate: true
          message: |
            ## :loudspeaker: Chromatic has been deployed! (${{ github.sha }})
            :books: Storybook: ${{ steps.chromatic.outputs.storybookUrl }}
            :gear: Build: ${{ steps.chromatic.outputs.buildUrl }}
